version: "3.9"
services:
    api:
        build: .
        ports:
            - "80:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Password123!"
            ACCEPT_EULA: "Y"